# Generated by Django 5.1.7 on 2025-03-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSprites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_default', models.URLField(blank=True, null=True)),
                ('front_shiny', models.URLField(blank=True, null=True)),
                ('front_female', models.URLField(blank=True, null=True)),
                ('front_shiny_female', models.URLField(blank=True, null=True)),
                ('back_default', models.URLField(blank=True, null=True)),
                ('back_shiny', models.URLField(blank=True, null=True)),
                ('back_female', models.URLField(blank=True, null=True)),
                ('back_shiny_female', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonListViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField()),
                ('total_pages', models.IntegerField()),
                ('pokemons', models.ManyToManyField(to='pokemons.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('next', models.URLField(blank=True, null=True)),
                ('previous', models.URLField(blank=True, null=True)),
                ('results', models.ManyToManyField(to='pokemons.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemonsprites'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemons.pokemontype'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemontypedetails'),
        ),
    ]
